export enum ActionType {
    LOAD_ITEMS = 'LOAD_ITEMS',
    CREATE = 'CREATE',
    EDIT = 'EDIT',
    DELETE = 'DELETE',
    GET = 'GET',
    SET = 'SET',
    SELECT = 'SELECT',
    SET_EDIT_MODE = 'SET_EDIT_MODE',
    SET_LOADING = 'SET_LOADING',
    SET_SUBMITTING = 'SET_SUBMITTING',
    SET_FILTERING = 'SET_FILTERING',
    ADD_PREDICATE = 'ADD_PREDICATE',
    RESET_PREDICATE = 'RESET_PREDICATE',
    SET_PAGING_PARAMS = 'SET_PAGING_PARAMS'
}
